# Name of workflow
name: Node CI

# Trigger the workflow on push or pull request
on:
  - push
  # - pull_request

jobs:
  lint:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    # strategy:
    #   # Node versions list
    #   matrix:
    #     node-version: [14.x]

    steps:
      - name: Run linter
        # Run Linter
        run: make lint
        # Add Code Climate secret key
        # env:
        #   CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        # with:
        #   coverageCommand: make test-coverage
        #   debug: true